Now uses MiscFixed for font when /usr/share/fonts/ucs-miscfixed exists. This fixes font size on Fedora (14) for G15. Added some missing files into bazaar. Removed PyGTK module check as it prevents RPMs from being built (when DISPLAY is not set). There is no need for this check anyway as pkg-config is used.

diff --git a/rel-gnome15 b/rel-gnome15
--- a/rel-gnome15
+++ b/rel-gnome15
@@ -218,12 +218,12 @@ then for i in $modules
          changelog_file="./${module_name}-${version}/debian/changelog"
          changelog_version=$(head -1 "${changelog_file}"|awk '{ print $2 }'|tr -d '('|tr -d ')')
          changes_file=${module_name}_${changelog_version}_source.changes
-         if [ -f ${changes_file} ]
-         then if ! dput ppa:tanktarta/gnome15 ${changes_file}
-              then echo $0: dput failed" >&2
+         if [ -f "${changes_file}" ]
+         then if ! dput -f ppa:gnome15-team/${dist} ${changes_file}
+              then echo "$0: dput failed" >&2
                    exit 1
               fi
-         else echo "$0: no changes file $changes_file, did you build source (-s)" >&2
+         else echo "$0: no changes file ${changes_file}, did you build source with -s" >&2
               exit 1
          fi
          popd >/dev/null >&1
